version: '3.6'

services:
  template:
    container_name: h08-hasura-auth-webhook
    image: localhost:5000/h08-hasura-auth-webhook:latest
    ports:
      - 3010:3000
    hostname: 'docker'
    env_file:
      ./.env
    volumes:
      - ./:/home/app/function
      - /home/app/function/node_modules
    networks:
      h08_network:
        ipv4_address: 10.0.1.10
networks:
    h08_network:
        external: true
